"""Skulk extension (plugin) system.

Separately installed packages register a factory in the ``skulk.extensions``
entry-point group; Skulk discovers them at startup and calls their hooks as
first-class citizens of the fabric. See :mod:`skulk.extensions.types` for the
contract and its invariants, and :mod:`skulk.extensions.loader` for
discovery, version gating, and guarded dispatch.
"""

from skulk.extensions.calls import (
    DEFAULT_CALL_TIMEOUT_SECONDS,
    MAX_CALL_PAYLOAD_BYTES,
    MAX_CALL_TIMEOUT_SECONDS,
    CapabilityCall,
    CapabilityError,
    CapabilityErrorCode,
    CapabilityResult,
    call_failure,
)
from skulk.extensions.capabilities import (
    CapabilityDescriptor,
    CapabilityIoMode,
    descriptor_revision,
)
from skulk.extensions.loader import (
    ENTRY_POINT_GROUP,
    LoadedExtensions,
    load_extensions,
    resolve_skulk_version,
)
from skulk.extensions.speech import (
    REALTIME_STT_CAPABILITY_DESCRIPTOR,
    STT_CAPABILITY_DESCRIPTOR,
    TTS_CAPABILITY_DESCRIPTOR,
    BuiltinSpeechProvider,
)
from skulk.extensions.streams import (
    MAX_INLINE_MEDIA_BYTES,
    BlobMediaAttachment,
    CapabilityStreamCancel,
    CapabilityStreamError,
    CapabilityStreamErrorCode,
    CapabilityStreamFrame,
    CapabilityStreamInput,
    CapabilityStreamReceiveBatch,
    CapabilityStreamReceiver,
    CapabilityStreamSession,
    InlineMediaAttachment,
    MediaAttachment,
    StreamDirection,
    decode_capability_stream_frame,
    encode_capability_stream_frame,
)
from skulk.extensions.telemetry import ClusterNodeView, snapshot_cluster
from skulk.extensions.types import (
    AdvertiseCapability,
    BaseChatMiddleware,
    CallCapability,
    CapabilityCallHandler,
    CapabilityInputStreamHandler,
    CapabilityProvider,
    CapabilityReadiness,
    CapabilityStreamAdmissionHandler,
    CapabilityStreamHandler,
    ChatMiddleware,
    ChatResponseSummary,
    DescribeNode,
    EmbedTexts,
    ExtensionContext,
    ReadClusterTelemetry,
    SkulkExtension,
    StreamCapability,
    SupportsExtensionShutdown,
    SupportsExtensionStartup,
    WithdrawCapability,
)
from skulk.extensions.vad import (
    VAD_CAPABILITY_DESCRIPTOR,
    BuiltinVadProvider,
    StreamingPcm16Resampler,
    VadConfig,
    VadTurnEvent,
    VoiceActivityDetector,
)
from skulk.extensions.validation import validate_against_schema

__all__ = [
    "DEFAULT_CALL_TIMEOUT_SECONDS",
    "ENTRY_POINT_GROUP",
    "MAX_CALL_PAYLOAD_BYTES",
    "MAX_CALL_TIMEOUT_SECONDS",
    "MAX_INLINE_MEDIA_BYTES",
    "AdvertiseCapability",
    "BaseChatMiddleware",
    "BlobMediaAttachment",
    "BuiltinSpeechProvider",
    "BuiltinVadProvider",
    "CallCapability",
    "CapabilityCall",
    "CapabilityCallHandler",
    "CapabilityInputStreamHandler",
    "CapabilityDescriptor",
    "CapabilityError",
    "CapabilityErrorCode",
    "CapabilityResult",
    "CapabilityIoMode",
    "CapabilityProvider",
    "CapabilityReadiness",
    "CapabilityStreamError",
    "CapabilityStreamErrorCode",
    "CapabilityStreamFrame",
    "CapabilityStreamInput",
    "CapabilityStreamCancel",
    "CapabilityStreamAdmissionHandler",
    "CapabilityStreamHandler",
    "CapabilityStreamReceiveBatch",
    "CapabilityStreamReceiver",
    "CapabilityStreamSession",
    "ChatMiddleware",
    "ChatResponseSummary",
    "ClusterNodeView",
    "DescribeNode",
    "EmbedTexts",
    "ExtensionContext",
    "InlineMediaAttachment",
    "LoadedExtensions",
    "MediaAttachment",
    "ReadClusterTelemetry",
    "REALTIME_STT_CAPABILITY_DESCRIPTOR",
    "STT_CAPABILITY_DESCRIPTOR",
    "StreamingPcm16Resampler",
    "SkulkExtension",
    "SupportsExtensionStartup",
    "SupportsExtensionShutdown",
    "TTS_CAPABILITY_DESCRIPTOR",
    "VAD_CAPABILITY_DESCRIPTOR",
    "VadConfig",
    "VadTurnEvent",
    "VoiceActivityDetector",
    "StreamDirection",
    "StreamCapability",
    "WithdrawCapability",
    "call_failure",
    "descriptor_revision",
    "decode_capability_stream_frame",
    "encode_capability_stream_frame",
    "load_extensions",
    "resolve_skulk_version",
    "snapshot_cluster",
    "validate_against_schema",
]
