// Copyright 2025 Foxlight Foundation

import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// The OpenAPI plugin generates a sidebar definition that uses category links
// with tag pages.  Importing it directly (instead of autogenerated) ensures
// the tag pages are recognised as category index pages so
// useCurrentSidebarCategory() works at build time.
import apiSidebar from "./docs/api/sidebar.ts";

const sidebars: SidebarsConfig = {
  guidesSidebar: [
    {
      type: "doc",
      id: "intro",
      label: "Introduction",
    },
    {
      type: "category",
      label: "Guides",
      collapsed: false,
      items: [
        "install",
        "build-and-runtime",
        "node-doctor",
        "human-release-qualification",
        "api-guide",
        {
          type: "category",
          label: "GPU Nodes",
          collapsed: false,
          items: ["nvidia-cuda-nodes", "amd-strix-halo-nodes", "vllm-engine"],
        },
        "speech-fabric-realtime",
        "speculative-decoding",
        "model-store",
        "model-cards",
        "model-capabilities",
        "operations",
        "extensions",
        "controller-integration",
        "run-skulk-as-a-service",
        "thunderbolt-clustering",
        {
          type: "category",
          label: "Tailscale",
          collapsed: false,
          items: ["tailscale", "tailscale-clustering"],
        },
        "kv-cache-backends",
        "external-logging",
        "tracing",
        "mobile-dashboard",
        "integrations",
        {
          type: "category",
          label: "Model Behaviors",
          items: [
            "model-behaviors/gemma4",
            "model-behaviors/gpt-oss",
            "model-behaviors/deepseek-v32",
          ],
        },
        "cluster-communication",
        "architecture",
        "architecture-reference",
        {
          type: "category",
          label: "Release Notes",
          items: ["release-notes/1.5.1", "release-notes/1.5.0", "release-notes/1.4.1", "release-notes/1.4.0", "release-notes/1.3.1", "release-notes/1.3.0", "release-notes/1.2.0", "release-notes/1.1.0", "release-notes/1.0.3", "release-notes/1.0.2"],
        },
      ],
    },
  ],

  apiSidebar,
};

export default sidebars;
